import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import { StackProvider } from '../components/providers/StackProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'headcraftAI - AI-Generated Professional Headshots',
  description: 'Get professional headshots generated by AI in minutes.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StackProvider>
          {children}
          <Toaster />
        </StackProvider>
      </body>
    </html>
  );
}
